// File emission for lesson-foundry — generates defense artifacts.
// Pure functions that return { path, content } pairs; caller writes them.

import { clusterName, clusterId, clusterMembers, extractLiteralPattern, escapeRegex } from './route.mjs';

/**
 * Build the grep-gate JSON descriptor for a LINT cluster.
 * Returns { path, content } where path is relative to outDir.
 */
export function buildLintDescriptor(name, findings) {
  const literal = extractLiteralPattern(findings);
  const pattern = literal ? escapeRegex(literal) : clusterName(findings).replace(/-/g, '.*');

  const descriptor = {
    // Stable, prose-independent cluster key. The gate credits the descriptor by
    // this id even if the slug-derived filename below has since drifted or been
    // renamed during refinement. Kept first so it survives a hand-edit at the top.
    id: clusterId(findings),
    // Durable banking identity: overlap with these survives growth AND merges.
    members: clusterMembers(findings),
    name,
    pattern,
    paths: ['**'],
    message: `lesson-foundry: recurring finding — ${findings[0]?.desc ?? name}`,
  };

  return {
    path: `${name}.lint.json`,
    content: JSON.stringify(descriptor, null, 2) + '\n',
  };
}

/**
 * Build the runnable check script for a LINT cluster.
 * Returns { path, content }.
 */
export function buildCheckScript(name, findings) {
  const literal = extractLiteralPattern(findings);
  const pattern = literal ? escapeRegex(literal) : clusterName(findings).replace(/-/g, '.*');
  const desc = (findings[0]?.desc ?? name).replace(/`/g, "'");

  // The gate must never trip on itself. We skip VCS/dependency dirs and the
  // generated lessons output directory, and we skip this script's own file by
  // basename so the gate only ever flags genuine occurrences in source.
  const selfBasename = `check-${name}.mjs`;

  const content = `#!/usr/bin/env node
// Auto-generated by lesson-foundry — do not edit manually.
// Pattern gate: ${desc}

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const PATTERN = ${JSON.stringify(pattern)};
// This generated script itself contains PATTERN (above and in its header
// comment). Skip its own file so the gate never trips on itself.
const SELF = ${JSON.stringify(selfBasename)};
const SKIP_DIR = /^(?:node_modules|\\.git|\\.adlc)$/;
const SOURCE_FILE = /\\.(?:mjs|js|ts|tsx)$/;

const re = new RegExp(PATTERN);
const hits = [];

// Searched in-process instead of shelling out: stock Windows has no grep, and
// git grep is only available inside a repository with git installed.
function scan(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (!SKIP_DIR.test(entry.name)) scan(join(dir, entry.name));
      continue;
    }
    if (!entry.isFile()) continue;
    if (entry.name === SELF) continue;
    if (!SOURCE_FILE.test(entry.name)) continue;
    const file = join(dir, entry.name);
    for (const [i, text] of readFileSync(file, 'utf8').split('\\n').entries()) {
      if (re.test(text)) hits.push(\`\${file}:\${i + 1}:\${text}\`);
    }
  }
}

scan('.');

if (hits.length > 0) {
  console.error('check-${name}: FAIL — pattern found in repo:');
  console.error(hits.join('\\n'));
  process.exit(2);
}

console.log('check-${name}: no matches found — PASS');
process.exit(0);
`;

  return {
    path: `check-${name}.mjs`,
    content,
  };
}

/**
 * Build a SKILL.md stub for a SKILL cluster.
 * Returns { path, content }.
 */
export function buildSkillStub(name, findings, llmRefinement) {
  const count = findings.length;
  const category = findings[0]?.category ?? 'pattern';
  const desc = llmRefinement?.description ?? findings[0]?.desc ?? name;
  const rule = llmRefinement?.rule ?? `Avoid: ${findings[0]?.desc ?? name}`;
  const displayName = llmRefinement?.name ?? name;

  // Collect evidence quotes
  const evidenceQuotes = findings
    .slice(0, 3)
    .map((f) => {
      const parts = [];
      if (f.file) parts.push(`file: ${f.file}`);
      if (f.line) parts.push(`line: ${f.line}`);
      if (f.desc) parts.push(`finding: ${f.desc}`);
      return parts.join(', ');
    })
    .filter(Boolean);

  const evidenceSection = evidenceQuotes.length
    ? evidenceQuotes.map((e) => `- ${e}`).join('\n')
    : '- (no specific file evidence recorded)';

  const content = `---
name: ${displayName}
description: ${desc}
category: ${category}
mined-from: ${count} findings
cluster-id: ${clusterId(findings)}
cluster-members: ${clusterMembers(findings).join(' ')}
triggers:
  - ${category}
  - recurring-finding
  - lesson-foundry
---

# ${displayName}

## Rule

${rule}

## Evidence

Mined from ${count} finding${count === 1 ? '' : 's'}:

${evidenceSection}

## Rationale

This skill was auto-generated by lesson-foundry from recurring prosecution findings.
Apply this rule proactively to prevent re-encountering the same issue.
`;

  return {
    path: `${name}.SKILL.md`,
    content,
  };
}

/**
 * Build the interrogation template line for a SPEC-GAP cluster.
 * Returns a markdown line to append to interrogation-template.md.
 */
export function buildSpecGapLine(name, findings) {
  const count = findings.length;
  const desc = findings[0]?.desc ?? name;
  const category = findings[0]?.category ?? 'unknown';
  const id = clusterId(findings);
  // Two markers: the human-readable slug (legacy, kept for back-compat) and the
  // stable cluster-id. The gate credits either, so rewording the question — even
  // dropping the slug annotation — cannot orphan the lesson as long as the id
  // marker survives.
  const members = clusterMembers(findings).join(' ');
  return `- [ ] **[${category}]** ${desc} *(recurring in ${count} finding${count === 1 ? '' : 's'}, cluster: ${name}, cluster-id: ${id}, cluster-members: ${members})*\n`;
}

/**
 * Plan all emissions for a set of clusters.
 * Returns array of { cluster, route, files: [{path, content}], destination }.
 * outDir prefix is applied to paths.
 * llmRefinements: Map<clusterIndex, {name, description, rule}>
 */
export function planEmissions(clusters, allFindings, outDir, llmRefinements = new Map()) {
  const interrogationLines = [];
  const plan = [];

  for (const [idx, cluster] of clusters.entries()) {
    const findings = cluster.indices.map((i) => allFindings[i]);
    const route = cluster.route;
    const name = cluster.name;
    const refinement = llmRefinements.get(idx) ?? null;
    const files = [];

    if (route === 'lint') {
      files.push(buildLintDescriptor(name, findings));
      files.push(buildCheckScript(name, findings));
    } else if (route === 'skill') {
      files.push(buildSkillStub(name, findings, refinement));
    } else {
      // spec-gap — collect lines for interrogation-template.md
      interrogationLines.push(buildSpecGapLine(name, findings));
    }

    // Apply outDir prefix
    const prefixedFiles = files.map((f) => ({
      ...f,
      path: `${outDir}/${f.path}`,
    }));

    plan.push({
      cluster,
      route,
      files: prefixedFiles,
      destination:
        route === 'lint'
          ? `${outDir}/${name}.lint.json + ${outDir}/check-${name}.mjs`
          : route === 'skill'
            ? `${outDir}/${name}.SKILL.md`
            : `${outDir}/interrogation-template.md`,
    });
  }

  // Merge spec-gap lines into interrogation-template.md
  if (interrogationLines.length > 0) {
    const templatePath = `${outDir}/interrogation-template.md`;
    plan
      .filter((p) => p.route === 'spec-gap')
      .forEach((p) => {
        // All spec-gap entries share the same interrogation template file
        p.interrogationPath = templatePath;
      });

    // Add interrogation template as a synthetic "cluster" file entry
    plan.push({
      cluster: null,
      route: 'spec-gap-template',
      files: [
        {
          path: templatePath,
          content:
            `# Interrogation Template\n\n` +
            `Auto-generated by lesson-foundry. Answer these questions in your spec (P1).\n\n` +
            interrogationLines.join(''),
          append: true,
        },
      ],
      destination: templatePath,
    });
  }

  return plan;
}
